#!/bin/bash
D=$(dirname "$0")
"$D"/datalog csv | tee rtdata.csv | "$D"/data-convert | feedgnuplot --domain --dataid --stream 0.1 --xlen 20 --autolegend --lines --style "A_{Band-P2/A2}" 'dt 2' --style "G_{Band-P2/A2}" 'dt 2'
